#!/bin/bash
SRC="/Users/jeffasare/Documents/GitHub/To be Uploaded to website"
DEST="/Users/jeffasare/Documents/GitHub/jeffery-asare-site"

c() {
  local dir="$1" src="$2" dst="$3"
  if [ -f "$dir/$src" ]; then
    cp "$dir/$src" "$DEST/$dst"
    echo "✓  $dst"
  else
    echo "✗  NOT FOUND: $src"
  fi
}

EC="$SRC/Eclipse of the self"
PT="$SRC/Portraits"
RS="$SRC/Random Stories"

echo "=== Eclipse of the Self (14) ==="
c "$EC" "The Veil Speaks.JPG"          "ec-the-veil-speaks.jpg"
c "$EC" "Consumed by Shadow.JPG"        "ec-consumed-by-shadow.jpg"
c "$EC" "Before I Disappeared.JPG"      "ec-before-i-disappeared.jpg"
c "$EC" "Searching for Signs.JPG"       "ec-searching-for-signs.jpg"
c "$EC" "Unraveling in Colour.JPG"      "ec-unraveling-in-colour.jpg"
c "$EC" "Covered in Gold.jpg"           "ec-covered-in-gold.jpg"
c "$EC" "Still in the Glow.jpg"         "ec-still-in-the-glow.jpg"
c "$EC" "The Joy That Holds.jpg"        "ec-the-joy-that-holds.jpg"
c "$EC" "The Space Between.jpg"         "ec-the-space-between.jpg"
c "$EC" "No More Than a Shadow.jpg"     "ec-no-more-than-a-shadow.jpg"
c "$EC" "She Burns Bright.jpg"          "ec-she-burns-bright.jpg"
c "$EC" "Of Gold and Gravity.jpg"       "ec-of-gold-and-gravity.jpg"
c "$EC" "Before the Words Come.jpg"     "ec-before-the-words-come.jpg"
c "$EC" "Blood and Shadow.jpg"          "ec-blood-and-shadow.jpg"

echo ""
echo "=== Portraits (34) ==="
c "$PT" "Beyond the Surface.jpeg"        "pt-beyond-the-surface.jpg"
c "$PT" "Blinded by the Spotlight.jpg"   "pt-blinded-by-the-spotlight.jpg"
c "$PT" "Chaos of Desires.jpg"           "pt-chaos-of-desires.jpg"
c "$PT" "Limitations.jpg"                "pt-limitations.jpg"
c "$PT" "Mysteries Untold.jpg"           "pt-mysteries-untold.jpg"
c "$PT" "Petra.jpg"                      "pt-petra.jpg"
c "$PT" "Preparation.JPG"                "pt-preparation.jpg"
c "$PT" "Solace.jpg"                     "pt-solace.jpg"
c "$PT" "vicky.jpg"                      "pt-vicky.jpg"
c "$PT" "Almost Gone.JPG"                "pt-almost-gone.jpg"
c "$PT" "Red Hours.JPG"                  "pt-red-hours.jpg"
c "$PT" "Tender Distance.JPG"            "pt-tender-distance.jpg"
c "$PT" "Between Us.JPG"                 "pt-between-us.jpg"
c "$PT" "Before the Prayer.jpg"          "pt-before-the-prayer.jpg"
c "$PT" "Together Apart.jpg"             "pt-together-apart.jpg"
c "$PT" "The Crown.jpg"                  "pt-the-crown.jpg"
c "$PT" "Held by the Wind.jpg"           "pt-held-by-the-wind.jpg"
c "$PT" "Dressed in Sunlight.jpg"        "pt-dressed-in-sunlight.jpg"
c "$PT" "Burned Into Memory.jpg"         "pt-burned-into-memory.jpg"
c "$PT" "Quiet Reckoning.jpg"            "pt-quiet-reckoning.jpg"
c "$PT" "What the Light Missed.jpg"      "pt-what-the-light-missed.jpg"
c "$PT" "The Darker Hours.jpg"           "pt-the-darker-hours.jpg"
c "$PT" "Weight of Quiet.jpg"            "pt-weight-of-quiet.jpg"
c "$PT" "The Warmth I Carry.jpg"         "pt-the-warmth-i-carry.jpg"
c "$PT" "Half Light.jpg"                 "pt-half-light.jpg"
c "$PT" "The Still Hour.jpg"             "pt-the-still-hour.jpg"
c "$PT" "What Remains.jpg"               "pt-what-remains.jpg"
c "$PT" "Low Flame.jpg"                  "pt-low-flame.jpg"
c "$PT" "Unspoken.jpg"                   "pt-unspoken.jpg"
c "$PT" "Room for Silence.jpg"           "pt-room-for-silence.jpg"
c "$PT" "Golden Drift.jpg"               "pt-golden-drift.jpg"
c "$PT" "The Backs We Show.jpeg"         "pt-the-backs-we-show.jpg"
c "$PT" "Unnamed Departure.jpeg"         "pt-unnamed-departure.jpg"
c "$PT" "The Upward Gaze.jpg"            "pt-the-upward-gaze.jpg"

echo ""
echo "=== Random Stories (40) ==="
c "$RS" "Born of These Streets.JPG"            "rs-born-of-these-streets.jpg"
c "$RS" "The Daily Gathering.jpg"              "rs-the-daily-gathering.jpg"
c "$RS" "A Pause in the Day.JPG"               "rs-a-pause-in-the-day.jpg"
c "$RS" "Against the Wall.jpg"                 "rs-against-the-wall.jpg"
c "$RS" "At the Threshold.jpg"                 "rs-at-the-threshold.jpg"
c "$RS" "Beauty's Thorn.jpg"                   "rs-beautys-thorn.jpg"
c "$RS" "Concrete Memory.jpg"                  "rs-concrete-memory.jpg"
c "$RS" "Connected Steps.jpg"                  "rs-connected-steps.jpg"
c "$RS" "Deliberate Progress.jpg"              "rs-deliberate-progress.jpg"
c "$RS" "Divergent Views.JPG"                  "rs-divergent-views.jpg"
c "$RS" "Far and Near.JPG"                     "rs-far-and-near.jpg"
c "$RS" "Frequencies in Red.JPG"               "rs-frequencies-in-red.jpg"
c "$RS" "Full of Wonder.jpg"                   "rs-full-of-wonder.jpg"
c "$RS" "Going Somewhere.jpg"                  "rs-going-somewhere.jpg"
c "$RS" "Hope and Zeal.jpg"                    "rs-hope-and-zeal.jpg"
c "$RS" "In Full Colour.jpg"                   "rs-in-full-colour.jpg"
c "$RS" "Leaving or Arriving.JPG"              "rs-leaving-or-arriving.jpg"
c "$RS" "Making Something Real.jpg"            "rs-making-something-real.jpg"
c "$RS" "Old Routes.jpg"                       "rs-old-routes.jpg"
c "$RS" "Overlooked.jpg"                       "rs-overlooked.jpg"
c "$RS" "Pages and Promises.jpg"               "rs-pages-and-promises.jpg"
c "$RS" "Passage of Time.jpg"                  "rs-passage-of-time.jpg"
c "$RS" "Patient.jpg"                          "rs-patient.jpg"
c "$RS" "Reflections of Loyalty.jpg"           "rs-reflections-of-loyalty.jpg"
c "$RS" "Rolling Forward.jpg"                  "rs-rolling-forward.jpg"
c "$RS" "Shoreline Silence.jpeg"               "rs-shoreline-silence.jpg"
c "$RS" "Silhouette Companion.jpg"             "rs-silhouette-companion.jpg"
c "$RS" "Still Waters.jpg"                     "rs-still-waters.jpg"
c "$RS" "The Ascent.jpg"                       "rs-the-ascent.jpg"
c "$RS" "The Feast.jpeg"                       "rs-the-feast.jpg"
c "$RS" "The Golden Hour That Wasn't.JPG"      "rs-the-golden-hour-that-wasnt.jpg"
c "$RS" "The Long Way Home.jpg"                "rs-the-long-way-home.jpg"
c "$RS" "The Steps We Take.jpg"                "rs-the-steps-we-take.jpg"
c "$RS" "The Village.jpg"                      "rs-the-village.jpg"
c "$RS" "Time.JPG"                             "rs-time.jpg"
c "$RS" "Two Wheels and a Dream.jpg"           "rs-two-wheels-and-a-dream.jpg"
c "$RS" "Unlocking New Horizons.jpg"           "rs-unlocking-new-horizons.jpg"
c "$RS" "Walking into the Morning.jpg"         "rs-walking-into-the-morning.jpg"
c "$RS" "What Binds.jpg"                       "rs-what-binds.jpg"
c "$RS" "What She Bears.JPG"                   "rs-what-she-bears.jpg"

echo ""
echo "=== All done! ==="
echo "Total: 14 Eclipse + 34 Portraits + 40 Random Stories = 88 images"
read -p "Press any key to close..."
